### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jvolima** [TaiFile/MagaluCloud_Hackaton#1]
- [x] Setup `Next`
- [x] Deploy `Hello World` utilizando Terraform
- [x]  Geração de templates pelo frontend
- [x] Deploy da infraestrutura completa
